Инкремент 20:
kuzminal/go-url-shortener pull request #9
Opened 2023-11-10 07:34 UTC by kuzminal

Добавил генерация сертификатов и флаг для включения TLS

2023-11-15 20:42 UTC, avhitrov requested changes
1. Не нашел в коде реализации задания 14 инкремента. А именно: 
``` В случае успешного приёма запроса хендлер должен возвращать HTTP-статус 202 Accepted.
Фактический результат удаления может происходить позже — каким-либо образом оповещать пользователя об успешности или неуспешности не нужно.
Используйте паттерн fanIn для максимального наполнения буфера объектов обновления.
```
Вместо заданного хендлер делает синхронное удаление, из-за чего задача с организацией graceful shutdown сводится к совсем элементарным действиям. Следует устранить пробел в реализации ТЗ, не забыв при этом аккуратно и вовремя погасить все отложенные процедуры (горутины).
2. Не на месте инициализация контекста для graceful shutdown
3. Нарушено условие ТЗ в области приоритета конфигурации.

2023-11-15 20:42 UTC, avhitrov commented on cmd/shortener/main.go
> +	shutdownCtx, cancel := context.WithTimeout(context.Background(), config.ShutdownTimeout)
К моменту, когда придет время выполнить `srv.Shutdown(shutdownCtx)`, данный контекст уже безнадежно протухнет и гарантированно вызовет ошибку шатдауна. Место объявления этой переменной - внутри горутины с шатдауном или непосредственно перед ее вызовом. И последующего `defer cancel()`, естественно, тоже.

https://go.dev/play/p/D1fC-bEhhoL

2023-11-15 20:42 UTC, avhitrov commented on internal/config/config.go
> +	if ConfigFile != "" {
Нарушено условие приоритета. Любое значения из конфига должно переписываться параметрами запуска и переменными окружения.

2023-11-20 11:19 UTC, kuzminal commented
Добавил горутины и канали для снхронизации завершения всех задач

2023-11-22 23:34 UTC, avhitrov requested changes
Два неблокирующих замечания о выборе метода fanIn-fanOut и буферизованного канала. Два мелких бага, которые следует исправить для повышения чистоты кода: использовать другой контекст при возврате ошибки и выбросить ненужную  переменную.

2023-11-22 23:34 UTC, avhitrov commented on cmd/shortener/main.go
> +	idleConnectionsClosed := make(chan struct{}, 1)
Нет смысла делать канал буферизованным, в него все равно не ведется запись.

2023-11-22 23:34 UTC, avhitrov commented on cmd/shortener/main.go
> +			return fmt.Errorf("server shutdown: %w", ctx.Err())
Скорее всего, ошибка будет выглядеть одинаково, так как сюда мы провалимся только после прерывания обоих контекстов, но, наверное, правильнее будет здесь использовать
```suggestion
			return fmt.Errorf("server shutdown: %w", shutdownCtx.Err())
```
даже не "наверное", а "точно". Потому что ctx будет говорить о том, что его заканселили, а gracefulCtx - что он протух. В любом случае, это стоит покрыть тестами.

2023-11-22 23:34 UTC, avhitrov commented on cmd/shortener/main.go
> +			if !ok && len(semaphore) == 0 {
```suggestion
			<-idleConnectionsClosed
			if len(semaphore) == 0 {
```
ok в данном коде всегда будет равен false, так как запись в канал нигде не производится, он только закрывается после завершения Shutdown.

В остальном вполне грамотное решение.

2023-11-22 23:34 UTC, avhitrov commented on cmd/shortener/main.go
> +			}(removeRequest)
Хочу подсветить несколько тонких моментов в таком подходе.
1. Это будет реализация своего рода fanOut после fanIn.
2. Нарушится последовательность записи. Пришедшая первой запись вполне может попасть в базу пятой по счету. Хотя приходят записи сюда также из горутин, а это значит, что на последовательность мы можем забить.
3. Если в момент начала шатдауна в памяти будет болтаться много открытых из хендлера удаления горутин, то мы теоретически сможем словить ситуацию, когда значение `len(semaphore)` будет равно нулю, но при этом еще будут оставаться задания на удаление.

Гарантированно дождаться завершения всех открытых горутин можно с помощью WaitGroup, но я не буду на этом настаивать. В качестве учебного примера или решения для не слишком дотошных систем, вроде банковских, данное решение вполне подходит.

2023-11-23 15:09 UTC, kuzminal commented
Поменял контекст в ошибке и добавил тест на проверку текста ошибки
Увеличил в принципе покрытие тестами

2023-11-23 20:16 UTC, kuzminal commented
и все-таки попробовал добавил waitgroup вместо семафоров

2023-11-27 22:07 UTC, avhitrov approved these changes
Отлично!

2023-11-30 21:10 UTC, merged